server:
  port: 8080

# database HikariCP相关配置
spring:
  datasource:
    url: jdbc:mysql://sandbox-starcoin-instance-1-cluster.cluster-ct4tlgfmee0j.ap-southeast-1.rds.amazonaws.com/ido_server?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: admin
    password: OdeWzZNalcTPk2LAo0Lg

---
## redis config
spring:
  redis:
    # Redis默认情况下有16个分片，这里配置具体使用的分片
    database: 0
    host: sandbox-starcoin-redis.xplek9.ng.0001.apse1.cache.amazonaws.com
    port: 6379
    password:
    timeout: 30000
    lettuce:
      pool:
        max-active: 16   # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 4     # 连接池中的最大空闲连接
        min-idle: 0     # 连接池中的最小空闲连接
        max-wait: 10000    # 连接池最大阻塞等待时间（使用负值表示没有限制）

## 日志配置
logging:
  # 日志级别
  logLevel: INFO
  # 日志保留天数，默认10天
  maxHistory: 5


## ------------------------------业务相关配置写到下面-------------------------
gamefi:
  common:
    url: https://main-seed.starcoin.org
    chain-id: 1
  aww:
    common:
      contract-address: "0x606723c9a16a26cb85415c98d43f4386"
    websocket:
      websocket-host: 10.13.22.40
      websocket-port: 9870
    content:
      aww-module: "AWW"
      arm-module: "ARM"
      aww-game-module: "AWWGame"
      market-module: "ARMMarket"
      grant-module: "Grant"
      scripts-module: "AWWScripts"
      nft-name: "aww arm"
      title-page-image: "https://test.kikoswap.com/v1/nft/image/group/1"
      description: "aww arms"
      image-info-api: "https://test.kikoswap.com/v1/nft/image/info/"
  bob:
    common:
      contract-address: "0x9b996121ea29b50c6213558e34120e5c"
    websocket:
      websocket-host: 60.205.3.84
      websocket-port: 8970
    content:
      bob-suffix: "::BOBConfigV1200::Config"
      race-module: "BOBNormalRaceV1200"
      bobSuffix-normal-ticket: "BOBNormalTicketV1200"
      bobSuffix-senior-ticket: "BOBSeniorTicketV1200"
      nft-name: "0x7D6409B9974e68f969c92554422cA19b::ARM2::ARMMeta,0x7D6409B9974e68f969c92554422cA19b::ARM2::ARMBody,0x00000000000000000000000000000001::STC::STC/"
      image-info-api: "https://test.armwrestwar.com/v1/aww/normal/getImage/"
      history-race: ""


